### PR TITLE
Add whenever gem

### PR DESCRIPTION
**Pull request by aitorlb**
Add `whenever` gem

I basically copied what was done here:
https://gitlab.coditdev.net/decidim/decidim-codit-demo-app/commit/e58a2e63c471f616f4c05065cb56b7619cd72577

Although in here the application.rb file isn't modified:
https://github.com/CodiTramuntana/decidim-barcelona_energia-app/commit/dd755aef62df0e71e871cf5f1a481219f46fccb2

### CODE REVIEW

**Comment by tramuntanal** [comment]
@MarcReniu @isaacmg410, @aitorlb have probably found a bug because the active_job backend isn't configured to delayed_job in barcelona energia and probably some other installation.
Can you check please?

**Comment by aitorlb** [comment]
@tramuntanal I added the whenever gem and a test, but dont know if it's that much help.
Just so you know, the `schedule.jobs[:rake]` used in the test is the following:
>[{:task=>"decidim:metrics:all", :every=>[1 day, {:at=>"2:00 am"}], :command=>"cd :path && :environment_variable=:environment :bundle_command rake :task --silent :output"}]

**Comment by MarcReniu** [comment]
Why adding `whenever-test` gem and a spec for rake tasks? I mean, metrics rake task has been already tested in `decidim`.

**Comment by aitorlb** [comment]
You're right @MarcReniu , that's why I said that I didnt know if it was of much help...
Should I revert back to the initial commit @tramuntanal ?

**Pull request merged**
