### PR TITLE
Upgrading Nokogiri from 1.13.3 to 1.13.4

### PR DESCRIPTION
**Pull request by ClaudiaMoPr**
I changed the Gemfile to update the Nokogiri gem to 1.13.4 because of the security alerts of dependant bot.

### CODE REVIEW

**Comment by ClaudiaMoPr** [comment]
I had to fix an error because I didn't change the version correctly the first time now it works properly.

**Comment by ClaudiaMoPr** [comment]
And now I fixed an offense that rubocop found.

**Comment by ClaudiaMoPr** [comment]
I added the Gemfile.lock

**Comment by tramuntanal** [comment]
Thanks you for your path @ClaudiaMoPr !

As some high level guidances when doing PR:

- beware to not disclose any private information (it is not the case in this PR)
- No need to explain what you did by commenting on each commit, the title of each commit should already give this information
- Always explain what the PR is doing: solve this, implement that feature, etc.. in the current PR explaing which security problems it's solving
- comment anything that you thing may help on the review, if you find necessary

**Review by LauraJaimeC — DISMISSED** [review]

**Review by LauraJaimeC — APPROVED** [review]

**Pull request merged**
